services:
  - type: web
    name: flask-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false

  - type: worker
    name: bot-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
